name: Release
on:
  release:
    types:
      - released
jobs:
  release:
    name: Build Release
    runs-on: ubuntu-24.04
    outputs:
      name: "An output"
    steps:
      - name: "Run"
        run: |
          echo "Hello, world!"
      - name: "Write to outputs"
        run: |
          echo "test=value" >> $GITHUB_OUTPUT

  external:
    name: External Job
    uses: ./.github/workflows/external.yml
    needs: release
